import { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
    {
        id: "1",
        name: "Fresh Organic Eggs",
        businessType: "livestock",
        unit: "pcs",
        priceUnit: "pcs",
        currentPrice: 350,
        currentStock: 50,
        stockHistory: [],
        priceHistory: [],
        createdAt: new Date(),
        createdBy: "admin",
        images: ["https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=800"], // Eggs
        description: "Farm fresh organic eggs, collected daily from free-range chickens.",
        isAvailableForSale: true,
    },
    {
        id: "2",
        name: "Green Spinach (Saag)",
        businessType: "crop",
        unit: "kg",
        priceUnit: "kg",
        currentPrice: 80,
        currentStock: 20,
        stockHistory: [],
        priceHistory: [],
        createdAt: new Date(),
        createdBy: "admin",
        images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&q=80&w=800"], // Spinach
        description: "Freshly harvested organic spinach.",
        isAvailableForSale: true,
    },
    {
        id: "3",
        name: "Local Goat Meat",
        businessType: "livestock",
        unit: "kg",
        priceUnit: "kg",
        currentPrice: 1200,
        currentStock: 10,
        stockHistory: [],
        priceHistory: [],
        createdAt: new Date(),
        createdBy: "admin",
        images: ["https://images.unsplash.com/photo-1606211475515-534570dfba41?q=80&w=1964&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"], // Meat
        description: "Premium quality local goat meat.",
        isAvailableForSale: true,
    },
    {
        id: "4",
        name: "Organic Honey",
        businessType: "product",
        unit: "pcs",
        priceUnit: "pcs",
        currentPrice: 800,
        currentStock: 15,
        stockHistory: [],
        priceHistory: [],
        createdAt: new Date(),
        createdBy: "admin",
        images: ["https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800"], // Honey
        description: "Pure organic honey from our apiary.",
        isAvailableForSale: true,
    },
    {
        id: "5",
        name: "Tractor Rental (Per Hour)",
        businessType: "asset",
        unit: "pcs",
        priceUnit: "pcs",
        currentPrice: 2500,
        currentStock: 1,
        stockHistory: [],
        priceHistory: [],
        createdAt: new Date(),
        createdBy: "admin",
        images: [], // Tractor images removed to fix preload warning
        description: "Heavy duty tractor available for rental services.",
        isAvailableForSale: false,
    }
];

export const MOCK_BLOG_POSTS = [
    {
        id: "post-1",
        title: "The Joy of Organic Farming",
        slug: "joy-of-organic-farming",
        excerpt: "Discover why organic farming is better for your health and the environment.",
        content: "Organic farming is more than just a trend; it's a commitment to the health of our planet and ourselves. By avoiding synthetic pesticides and fertilizers, we allow nature to take its course, resulting in produce that is richer in nutrients and free from harmful chemicals...",
        imageUrl: "https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=800",
        date: new Date().toISOString(),
        author: "Farmer Santosh",
        readTime: 5,
        categories: ["Organic", "Sustainability"],
        tags: ["farming", "nature", "health"]
    },
    {
        id: "post-2",
        title: "Raising Free-Range Chickens",
        slug: "raising-free-range-chickens",
        excerpt: "Learn the secrets to happy, healthy, and productive free-range chickens.",
        content: "Happy chickens make the best eggs! In this post, we discuss the importance of space, natural forage, and a stress-free environment for our feathered friends. From building the perfect coop to understanding their social behavior...",
        imageUrl: "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?auto=format&fit=crop&q=80&w=800",
        date: new Date().toISOString(),
        author: "Admin",
        readTime: 7,
        categories: ["Livestock", "Poultry"],
        tags: ["chickens", "eggs", "farming"]
    },
    {
        id: "post-3",
        title: "Organic Slow Farming",
        slug: "organic-slow-farming",
        excerpt: "Embracing the rhythm of nature for sustainable agriculture and better health.",
        content: "Slow farming is about returning to the roots of agriculture, where quality takes precedence over quantity. Unlike industrial farming, which focuses on speed and mass production, organic slow farming emphasizes soil health, biodiversity, and the natural growth cycles of crops. This approach not only produces food that is richer in nutrients and flavor but also preserves the environment for future generations. By choosing slow-farmed organic produce, you are supporting a system that values the earth and sustainable living.",
        imageUrl: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?auto=format&fit=crop&q=80&w=800",
        date: new Date().toISOString(),
        author: "Farmer Santosh",
        readTime: 6,
        categories: ["Organic", "Sustainability"],
        tags: ["farming", "slow food", "organic"]
    },
    {
        id: "post-4",
        title: "How Much Protein Do We Really Need?",
        slug: "how-much-protein-we-need",
        excerpt: "Understanding daily protein requirements for a balanced and healthy lifestyle.",
        content: "Protein is a building block of life, essential for repairing tissues and making enzymes and hormones. But how much do we really need? The recommended dietary allowance (RDA) is 0.8 grams of protein per kilogram of body weight, but this can vary based on activity level, age, and health goals. Athletes may need more, while sedentary individuals might need less. It's important to get protein from a variety of sources, including lean meats, eggs, dairy, beans, and nuts, to ensure a complete amino acid profile.",
        imageUrl: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=800",
        date: new Date().toISOString(),
        author: "Nutrition Expert",
        readTime: 5,
        categories: ["Health", "Nutrition"],
        tags: ["protein", "health", "diet"]
    },
    {
        id: "post-5",
        title: "Better Parenting Tips for Parents of Teenagers",
        slug: "parenting-tips-for-teenagers",
        excerpt: "Navigating the teenage years with patience, understanding, and effective communication.",
        content: "Parenting teenagers can be challenging, but it's also a rewarding journey of growth for both parents and children. Key tips include active listening, respecting their growing need for privacy and independence, and maintaining open lines of communication. Avoid judgment and criticism; instead, offer support and guidance. Set clear boundaries but be willing to negotiate. Remember, your teenager is learning to navigate the world on their own, and your steady, supportive presence is their strongest anchor.",
        imageUrl: "https://images.unsplash.com/photo-1591114227092-2fe654224c2d?auto=format&fit=crop&q=80&w=800",
        date: new Date().toISOString(),
        author: "Family Counselor",
        readTime: 8,
        categories: ["Lifestyle", "Family"],
        tags: ["parenting", "teenagers", "family"]
    }
];
