// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNuihfO1Cu7tDx0WEo0VuxG0SeRVEGmLA',
    appId: '1:39694516542:web:b4680bcd7c54eb885fac6f',
    messagingSenderId: '39694516542',
    projectId: 'farmmanagement-fc956',
    authDomain: 'farmmanagement-fc956.firebaseapp.com',
    storageBucket: 'farmmanagement-fc956.firebasestorage.app',
    measurementId: 'G-652CHXH0FY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdIlEKWYAFYBQsjKXsut5N1s5HDwcKsWE',
    appId: '1:39694516542:ios:6f291a1e239401dc5fac6f',
    messagingSenderId: '39694516542',
    projectId: 'farmmanagement-fc956',
    storageBucket: 'farmmanagement-fc956.firebasestorage.app',
    iosClientId: '39694516542-h3nikttlpalrel2j2jhsaceh3oc5okoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdIlEKWYAFYBQsjKXsut5N1s5HDwcKsWE',
    appId: '1:39694516542:ios:6f291a1e239401dc5fac6f',
    messagingSenderId: '39694516542',
    projectId: 'farmmanagement-fc956',
    storageBucket: 'farmmanagement-fc956.firebasestorage.app',
    iosClientId: '39694516542-h3nikttlpalrel2j2jhsaceh3oc5okoi.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmManagementApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMp_inTSC_faLgXGewWtZM0wixWf331XQ',
    appId: '1:39694516542:android:0c4b7b1742c81d2e5fac6f',
    messagingSenderId: '39694516542',
    projectId: 'farmmanagement-fc956',
    storageBucket: 'farmmanagement-fc956.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNuihfO1Cu7tDx0WEo0VuxG0SeRVEGmLA',
    appId: '1:39694516542:web:c2d340a160e4381c5fac6f',
    messagingSenderId: '39694516542',
    projectId: 'farmmanagement-fc956',
    authDomain: 'farmmanagement-fc956.firebaseapp.com',
    storageBucket: 'farmmanagement-fc956.firebasestorage.app',
    measurementId: 'G-T18HZ6E58M',
  );

}